# Generated by Django 4.1.5 on 2023-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
